### ISSUE TITLE
is it possible to add a 'cancel' button?

### ISSUE THREAD

**Issue by ipeisong** [JonasGessner/JGProgressHUD#11]
Like in Flipboard loading view, there is a dismiss button to cancel the loading.
![image 3](https://cloud.githubusercontent.com/assets/1235739/4040080/d3f5e6e8-2cdb-11e4-9392-1f99f44a9860.png)

**Comment by gerchicov-bp** [comment]
@JohnCoates After 2.5 years do you plan to add a cancel button which is usually necessary but libraries don't provide it?

**Comment by JohnCoates** [comment]
@gerchicov-bp I think you tagged the wrong person. I submitted a pull request to this project once but that's it

**Comment by JonasGessner** [comment]
@gerchicov-bp why so salty? Did you read the previous posts in this thread? A hud is not a control, it shouldn't have any buttons by design. However, as I already mentioned 2,5 years ago, there is a callback for touch events which can be used like a button callback. There is even a demo for the touch handler in the example project.

**Comment by gerchicov-bp** [comment]
@JonasGessner I saw a lot of huds and `MBProgressHud` has proper look with dismiss button. They did it so you can do it too.
Why dismiss button instead of touch events? Situation 1: an user looks at progress view and it is not obvious that he should hit this view to cancel. Situation 2: an user touches this view, maybe accidentally and it call cancel action immediately (I hope you won't suggest to present additional alert over another alert).

**Comment by JonasGessner** [comment]
Have you even once looked at the example project? Both things you mentioned are not a problem there.

And if you really insist on adding a button you can still do it by adding a custom content view to the HUD.

**Comment by bullda** [comment]
So, after 2.5 years again. Is there a cancel button now?

**Comment by JonasGessner** [comment]
@bullda I edited your comment to make it sound less childish. Try being less sassy when talking to people who publish their work for free.

There are several ways you could implement a "cancel" feature. There is even one in the example project: https://github.com/JonasGessner/JGProgressHUD/blob/master/Examples/JGProgressHUD-Tests/JGMainViewController.m#L114. I recommend looking at the examples and documentation before opening an issue/leaving a comment. In addition to the way shown in the example, it is theoretically also possible to add a custom indicator view to the hud that contains a button.

I still stand by the fact that if you want to add a cancel button, you probably shouldn't be using a HUD in the first place. A HUD should be used to display some sort of status for short to medium duration operations. Any longer or cancellable operations should, in most cases, have a dedicated UI in the app. If you look at how Apple uses HUDs (or used to, not sure if they still use any), they never had any user interactions. Having user interactions on a HUD is probably not the most intuitive user experience.

**Comment by DanijelHuis** [comment]
I just saw cancel button on MBProgressHUD and thought to check if JGProgressHUD supports it. I use hud mainly for networking, cancel button is a really convenient way for user to cancel request in bad network connection or similar. 

I don't see a reason why a hud couldn't be interactable. It is more android-like feature, more flexible but doesn't look so nice and simple anymore. Ideally this button would show after some time, e.g. 10 sec. 

Just my thoughts. 
Thank you for your library! I used it in few apps so far and it works really good.
