### ISSUE TITLE
setting typeface

### ISSUE THREAD

**Issue by alirezat66** [JonasGessner/JGProgressHUD#123]
Hi dear, thanks for amazing library that you made. Can I set my font in text that showing with your dialog?

**Comment by JonasGessner** [comment]
Yes, the `JGProgressHUD` class exposes all its labels (https://github.com/JonasGessner/JGProgressHUD/blob/master/JGProgressHUD/JGProgressHUD/JGProgressHUD.h#L69), which means you can change the font of those labels.

Please look at documentation and header files next time before asking such a question because you could have easily found out that you can access the labels.
