### ISSUE TITLE
Can not archive in Xcode9 Swift4

### ISSUE THREAD

**Issue by CK11FOR333** [JonasGessner/JGProgressHUD#83]
I created a hud just like guide code.
Running in iPhone was find, but when I was archived that Xcode said hud need to add ? or ! .
I'm using swift4 and installing by CocoaPods with branch 2.0.
What's going on?

By the way, using swift3 in Xcode8 and installing manually with branch 1.4.1 is no problem.

**Comment by JonasGessner** [comment]
Please show me your code otherwise I can't help you with your problem. But it sounds like you're calling a function on an optional, which is why you get an error saying you need to unwrap the optional (using `!` or `?`). You can read up on optionals [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html#//apple_ref/doc/uid/TP40014097-CH5-ID330).
